### ISSUE TITLE
Missing some RPCs from rpc list

### ISSUE THREAD

**Issue by NexiusTailer** [Brunoo16/samp-packet-list#16]
Currently there are some missing outcoming RPCs, addition of which would be very useful:

- SpawnPlayer
- SetVehicleToRespawn
- RepairVehicle
- SetVehicleVelocity
- SetVehicleAngularVelocity
- AttachTrailerToVehicle
- DetachTrailerFromVehicle
- AddVehicleComponent (if there is an RPC to set it when vehicle is already created)
- ChangeVehicleColor (if there is an RPC to set it when vehicle is already created)
- ChangeVehiclePaintjob (if there is an RPC to set it when vehicle is already created)

**Comment by NexiusTailer** [comment]
**UPD:** Using OnOutcomingRPC for debugging I managed to figure out some of the IDs of the functions stated above:
SpawnPlayer = outcoming RPC 129
SetVehicleToRespawn = outcoming RPC 165 + outcoming RPC 164
RepairVehicle = outcoming RPC 147 + outcoming RPC 106
AddVehicleComponent, ChangeVehicleColor and ChangeVehiclePaintjob = outcoming RPC 96
SetVehicleVirtualWorld and SetPlayerVirtualWorld = outcoming RPC 165 (any vehicles just removed for player (me) if I isn't in the same vw, pretty interesting), and outcoming RPC 164 (if I beginning to stay in the same vw with vehicles) - so, this doesn't have direct similar RPCs, okay
AttachTrailerToVehicle = outcoming RPC 148
DetachTrailerFromVehicle = outcoming RPC 149

**Comment by NexiusTailer** [comment]
UPD 2:
I think more RPCs can be found even in such places (and there is still some ones that isn't presented in wiki, like RPC_ScmEvent or RPC_DestroyPickup):
https://github.com/IllidanS4/YSF/blob/master/src/RPCs.h#L64
https://github.com/oscar-broman/SKY/blob/master/src/RPCs.cpp#L12

**Comment by NexiusTailer** [comment]
Sorry for the possible flood or something, but I have a specific desire to add as much information as possible to this wiki since this is the only place where something is presented at all, however, the contained information is really not enough for the full development of something serious and large on pawn.raknet. So, I found a few more RPCs (but this time also incoming) that are equivalent to the following publics:

OnVehicleDeath = IRPC 136
OnPlayerClickTextDraw, OnPlayerClickPlayerTextDraw = IRPC 83
OnEnterExitModShop/OnVehicleMod/OnVehiclePaintjob/OnVehicleColor = IRPC 96
OnPlayerClickPlayer = IRPC 23

Other RPCs:
InitGame = ORPC 139
SrvNetStats = 102 (both IRPC and ORPC)
GameTimeUpdate = ORPC 60 (regularly sends to a player every few seconds)
GameModeRestart = ORPC 40
ConnectionRejected = 130 (probably ORPC)
DestroyPickup = ORPC 63
MoveObject = ORPC 99
InitMenu = ORPC 76
Create3DTextLabel = ORPC 36
AttachCameraToObject	= ORPC 81

**Comment by NexiusTailer** [comment]
And another idea (I'm really sorry for that mess, but these all important thing as you see xD) - what about adding information to all RPCs about names of natives or publics which are their counterpart. At the moment there is little uncertainty when some RPC are named for example SendDeathNotification (which doesn't give a direct understanding of which public is their analogue), while others are called similarly to the names of the same publics (OnPlayerPickupPickup).

**Comment by KashCherry** [comment]
Some info about your RPCs. Also I guess Bruno can add this to the wiki.
```C++
SpawnPlayer
RPC_RequestSpawn = 129;
PARAMS: uint32_t PlayerID

AttachTrailerToVehicle
RPC_ScrAttachTrailerToVehicle = 148;
PARAMS: uint16_t trailerid, uint16_t vehicleid

DetachTrailerFromVehicle
RPC_ScrDetachTrailerFromVehicle = 149;
PARAMS: uint16_t vehicleid

SetVehicleVelocity and SetVehicleAngularVelocity
RPC_ScrSetVehicleVelocity = 91;
PARAMS: uint8_t unknown, float vel_x, float vel_y, float vel_z;
```
Callbacks:
```C++
OnVehicleDeath
RPC_VehicleDestroyed = 136;
PARAMS: uint16_t vehicleid

OnPlayerClickPlayer
RPC_ClickPlayer = 23;
PARAMS: uint16_t clickedplayer, uint8_t source

OnPlayerClickTextDraw
RPC_ClickTextDraw = 83;
PARAMS: uint16_t clickedid;

OnEnterExitModShop/OnVehicleMod/OnVehiclePaintjob/OnVehicleColor
RPC_ScmEvent = 96;
PARAMS: uint32_t param1, uint32_t param2, uint32_t param3, uint32_t event
```
Other RPCs
```C++
not enough information, I don’t think I can help here :[
```

**Comment by NexiusTailer** [comment]
Another RPCs:
SetVehicleParamsEx = ORPC 24
InterpolateCamera = ORPC 82

**Comment by NexiusTailer** [comment]
Found another IDs which can be also useful:
PlayCrimeReportForPlayer = ORPC 112
CreateMenu = ORPC 76 (called with ORPC 77 when you show a menu for the first time)
EditObject = ORPC 117
EditAttachedObject = ORPC 116
SetPlayerShopName = ORPC 33
MoveObject = ORPC 99
SendClientCheck = ORPC 103

**Comment by Zorono** [comment]
Create3DTextLabel = RPC 36(https://github.com/BlastHackNet/mod_s0beit_sa-1/blob/dc9b3b13599a8b6325e566f567b5391b0b2a6dc8/bin/mod_sa/mod_sa.ini#L1462)
