### ISSUE TITLE
Missing some packets from packet list

### ISSUE THREAD

**Issue by NexiusTailer** [Brunoo16/samp-packet-list#19]
ID_MARKERS_SYNC - ID 208 and ID_RCON_RESPONCE - ID 202 isn't listed in outgoing/incoming packets.

Some other (but not so useful as above) packets can be found here:
https://github.com/cizaquita/FakeSAMP/blob/master/raknet/PacketEnumerations.h

Other notes:
Is seems that ID_CONNECTION_REQUEST_ACCEPTED and ID_CONNECTION_ATTEMPT_FAILED according to its names are outgoing packets, not incoming. Am I right?

**Comment by NexiusTailer** [comment]
I think there is also a link here you've forgotten about:

> ID_SPECTATING_SYNC (or ID_SPECTATOR_SYNC) - ID 212, ID_MARKERS_SYNC - ID 208 and ID_RCON_RESPONCE - ID 202 isn't listed in incoming packets.
> 
> Some other (but not so useful as above) packets can be found here:
> https://github.com/cizaquita/FakeSAMP/blob/master/raknet/PacketEnumerations.h

**Comment by NexiusTailer** [comment]
Maybe it is worth re-opening it because of this?

> I think there is also a link here you've forgotten about:
> 
> > ID_SPECTATING_SYNC (or ID_SPECTATOR_SYNC) - ID 212, ID_MARKERS_SYNC - ID 208 and ID_RCON_RESPONCE - ID 202 isn't listed in incoming packets.
> > Some other (but not so useful as above) packets can be found here:
> > https://github.com/cizaquita/FakeSAMP/blob/master/raknet/PacketEnumerations.h

**Comment by NexiusTailer** [comment]
I just update this issue to remind about the previous message...

**Comment by Dmitriy51** [comment]
https://github.com/Dmitriy51/RakNet-Packets-SA-MP/blob/main/Packets.txt
