### ISSUE TITLE
Mistake in RPC

### ISSUE THREAD

**Issue by Tim4ukys** [Brunoo16/samp-packet-list#30]
RU:
["GiveTakeDamage - 115"](https://github.com/BrunoBM16/samp-packet-list/wiki/RPC-List#givetakedamage---115) находится в группе входящих пакетов, хотя он исходящий.

EN:
["GiveTakeDamage-115"](https://github.com/BrunoBM16/samp-packet-list/wiki/RPC-List#givetakedamage---115) is in the incoming packet group, although it is outgoing.

**Comment by NexiusTailer** [comment]
It is both an incoming packet and outgoing.
