### ISSUE TITLE
missing parameter

### ISSUE THREAD

**Issue by samprapist** [Brunoo16/samp-packet-list#35]
in **03dl** for this package there is an additional custom skin id parameter after the skinid parameter

ShowActor - ID: 171

 **correct** UINT16 wActorID, UINT32 SkinID, **UINT32 CustomSkinID**(0 if not there) , float X, float Y, float Z, float Angle, float Health, bool Invulnerable

   **incorrect**  UINT16 wActorID, UINT32 SkinID, float X, float Y, float Z, float Angle, float Health, bool Invulnerable

**Comment by NexiusTailer** [comment]
Thanks, it was added [here](https://github.com/Brunoo16/samp-packet-list/wiki/0.3.DL-Specific-RPCs).
