### ISSUE TITLE
Wrong RPC Name: Update3DTextLabel - ID: 58

### ISSUE THREAD

**Issue by pitaya1001** [Brunoo16/samp-packet-list#38]
The RPC with id 58 does not "update", but rather hide the 3D Text label with the specified id.

See here for reference:
https://github.com/openmultiplayer/open.mp/blob/53e039797c1598ac21383e28bc78b9263e42057e/Shared/NetCode/textlabel.hpp#L49

**Comment by NexiusTailer** [comment]
Fixed, thanks.
